#!/bin/ksh

set -o errexit
set -o nounset

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/Bin
WWWROOT="/var/www/htdocs"
TMPDIR=$(mktemp -d)

uid=$(id -u)
publicip=$(ifconfig egress | grep inet |grep -v inet6 | cut -d ' ' -f2)


if [[ $uid -ne 0 ]]; then
	print $0 "you've got to run $0 as uid=0 \n"
	exit 1
fi

if [ ! -d "$WWWROOT/geodata.telecom.lobby" ]; then 
	mkdir "$WWWROOT/geodata.telecom.lobby"
fi

cd "$WWWROOT/geodata.telecom.lobby"
ctrl=
while [ -z $ctrl ]
do
	echo -n "Do you want to download SRTM data?"
	read ctrl
	case $ctrl in
		"yes")
			wget --mirror --convert-links --adjust-extension --page-requisites  --no-parent  --user-agent="Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" https://srtm.kurviger.de/
			mv srtm.kurvinger.de/* . && rm -rf srtm.kurvinger.de
			cd SRTM1
			find . -name "*.zip" | xargs -I {} mv {} .
			find . -not -name "*.zip" | xargs -I {} rm -rf {} 
			cd SRTM3
			find . -name "*.zip" | xargs -I {} mv {} .
			find . -not -name "*.zip" | xargs -I {} rm -rf {} 
			mkdir Landcover && cd Landcover
			wget http://rmw.recordist.com/landcover/
			cat index.html | grep -io '<a href=['"'"'"][^"'"'"']*['"'"'"]' | sed 's/<a href="/rmw.recordist.com\/landcover\//' | sed 's/"//' | awk -F, '$1 ~ "zip"' | xargs -I {} wget {}
			;;
		"no")
			;;
		*) 
			echo -n "please type yes or no"
			exit 1
			;;  
done
iso3166=
while [ -z $iso3166 ]
do
	echo -n "Type the country code ISO 3166 \n"
	read iso3166
	case $iso3166 in
		"ES") 
			if [[ ! -d "$WWWROOT/geodata.telecom.lobby/$iso3166" ]]; then
				mkdir "$WWWROOT/geodata.telecom.lobby/$iso3166"
			fi
			;;
		*)
			echo -n "Sorry for now only Spain is supported between LAT from 35 to 43 N\
				\n and LONG from 0 to 3 E and from 0 to 9 W \n"
			exit 1
			;;
done
ctrl=
while [ -z $ctrl ]
do
	echo -n "Do you want to download SRTM and Land coverdata? \
		\nbe careful they are more that 10GB\n"
	read ctrl
	case $ctrl in
		"yes")
			wget --mirror --convert-links --adjust-extension --page-requisites  --no-parent  --user-agent="Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" https://srtm.kurviger.de/
			mv srtm.kurvinger.de/* . && rm -rf srtm.kurvinger.de
			cd SRTM1
			find . -name "*.zip" | xargs -I {} mv {} .
			find . -not -name "*.zip" | xargs -I {} rm -rf {} 
			cd SRTM3
			find . -name "*.zip" | xargs -I {} mv {} .
			find . -not -name "*.zip" | xargs -I {} rm -rf {} 
			mkdir Landcover && cd Landcover
			wget http://rmw.recordist.com/landcover/
			cat index.html | grep -io '<a href=['"'"'"][^"'"'"']*['"'"'"]' | sed 's/<a href="/rmw.recordist.com\/landcover\//' | sed 's/"//' | awk -F, '$1 ~ "zip"' | xargs -I {} wget {}
			;;
		"no")
			;;
		*) 
			echo -n "please type yes or no \n"
			exit 1
			;;  
done
ctrl=
while [ -z $ctrl ]
do
	echo -n "Do you want to select SRTM and Land cover data \
		\nby country code?\n"
	read ctrl
	case $ctrl in
		"yes")
			if [ ! -d "$TMPDIR/SRTM3" ]; then
				mkdir "$TMPDIR/SRTM3"
			fi
			if [ ! -d "$TMPDIR/Landcover" ]; then
				mkdir "$TMPDIR/Landcover"
			fi
			filepath=
			file=
			nordwest=
			nordeast=
			for filepath in */*; do
				file=$(basename "$filepath") 
				nordwest=$(echo $file | grep -v "S" | grep -v "E")
				if [[ ! -z $nordwest ]]; then
					typeset -i lat=$(echo $nordwest | sed -e "s/.*N//g" -e "s/W.*//g")
					typeset -i long=$(echo $nordwest | sed -e "s/.*W//g" -e "s/\..*//g")
					if [[ $lat -ge 35 && $lat -le 43 && $long -ge 0 && $long -le 9 ]]; then
						if [[ "$filepath" == SRTM3* ]]; then
							cp $filepath "$TMPDIR/SRTM3"
						else
							cp $filepath "$TMPDIR/Landcover"
						fi
					fi
				fi
				nordeast=$(echo $file | grep -v "S" | grep -v "W")
				if [[ ! -z $nordeast ]]; then
					typeset -i lat=$(echo $nordeast | sed -e "s/.*N//g" -e "s/E.*//g")
					typeset -i long=$(echo $nordeast | sed -e "s/.*E//g" -e "s/\..*//g")
					if [[ $lat -ge 35 && $lat -le 43 && $long -ge 0 && $long -le 3 ]]; then
						if [[ "$filepath" == SRTM3* ]]; then
							cp $filepath "$TMPDIR/SRTM3"
						else
							cp $filepath "$TMPDIR/Landcover"
						fi
					fi
				fi
			 done
			mv "$TMPDIR/*" "$WWWROOT/geodata.telecom.lobby/$iso3166/"
			;;
		"no")
			;;
		*) 
			echo -n "please type yes or no"
			exit 1
			;;  
done


sed -i "s/\/PUBLICIP\//$publicip/g" src/etc/httpd.conf.geodata.telecom.lobby
install -o root -g wheel -m 0640 -b src/etc/httpd.conf.geodata.telecom.lobby /etc/

if [ -e "/etc/httpd.conf" ]; then 
	echo 'include "/etc/httpd.conf.geodata.telecom.lobby"' >> /etc/httpd.conf
	rcctl restart httpd
else
	install -o root -g wheel -m 0640 -b src/etc/httpd.conf /etc/
	install -o root -g wheel -m 0640 -b src/etc/httpd.conf.mime.types /etc/
	rcctl enable httpd
	rcctl start httpd
fi

